@startuml
entity Tree{
  .. Props ..
  + data: Array<TreeNode>
  + defaultExpandAll: boolean
  + expandedKeys(v-model): Array<string | number>
  + selectable: boolean
  + selectedKeys(v-model): Array<string | number> 
  + multiple: boolean
  + cancelable: boolean 
  + checkable: boolean 
  + checkStrictly: string 
  + checkedKeys(v-model): Array<string | number> 
  + childrenField: string 
  + valueField: string 
  + labelField: string 
  + remote: boolean 
  + loadData: (node: TreeNode) => Promise<void>
  + filterMethod: (filterText, node: TreeNode) => boolean  
  + virtualList: boolean 
  + accordion: boolean 
  + draggable: Boolea 

  .. Events ..
  + check: ({ checkedKeys, node, event, isChecked }) => void
  + expand: ({ expandedKeys, node, event, isExpanded }) => void
  + select: ({ selectedKeys, node, event, isSelected }) => void

  .. Methods ..
  + filter: (filterText) => void
  + selectNode: (value) => void
  + expandNode: (value) => void
  + checkNode: (value) => void
}

note right of Tree::defaultExpandAll
default false
是否默认展开所有节点，当有 expandedKeys 时,defaultExpandAll 将失效
end note

note right of Tree::checkStrictly
default: all
设置勾选策略来计算checkedKeys。
all为全部选中节点;
parent 为全部选中节点中的父节点（当父节点下所有子节点都选中时）;
child 为全部选中节点中的叶子节点
end note

note right of Tree::virtualList
是否使用虚拟滚动，需要设置tree的高度
end note

entity TreeNode{
  .. Props ..
  value: string | number
  label: string
  children?: TreeNode[]
  disabled?: boolean
  selectable?: boolean
  checkable?: boolean
  isLeaf?: boolean
  prefix?: string | (() => VNodeChild)
  suffix?: string | (() => VNodeChild)
}
Tree --|> TreeNode
@enduml
